//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCvEntities : DbContext
    {
        public DBCvEntities()
            : base("name=DBCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abouts> Abouts { get; set; }
        public virtual DbSet<Certificates> Certificates { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Educations> Educations { get; set; }
        public virtual DbSet<Experiences> Experiences { get; set; }
        public virtual DbSet<Interests> Interests { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<SocialMedia> SocialMedia { get; set; }
    }
}
